### ISSUE TITLE
是否可以限制一下多线程数

### ISSUE THREAD

**Issue by misaka123456** [soarqin/iQ2#2]
一般的动漫都是6min一端  共4端   是没问题的
但是我发现电影是3min一端   我好不容易把一部2h的电影进度条拉完   一共30多段
Ctrl+c后  发现是30多个线程一起跑   跑了10秒后就蜜汁停止  

我希望作者大大能把同时的下载数限制为4个   多余的可以在后台等待  不然的话就只能下载动漫  不能下载综艺电影了   TAT

感谢

**Comment by soarqin** [comment]
做了个新版，最多4线程下载，并且可以用`iQ2 r`来继续上次没下载完的进度，而不用重新打开网页拉一遍视频

**Comment by misaka123456** [comment]
感谢了
