### ISSUE TITLE
麻烦作者更新最新版本

### ISSUE THREAD

**Issue by YFTX2015** [soarqin/iQ2#7]
以前的貌似都失效了，几个月之前的，iQ2.exe打开就闪退

**Comment by mekaku** [comment]
用cmd运行不闪退，不过这工具不支持https，271现在全站https

**Comment by YFTX2015** [comment]
但是作者现在仍然能够搬运271动画并在动漫花园发布，难道用的不是这个工具？

**Comment by mekaku** [comment]
我也比较好奇，可能是作者自己更新了工具

**Comment by YFTX2015** [comment]
他现在不更新，估计是要保密，不想让别个用
